//
// Adaptive Vision Library 4.10.0.61766
// This file is a part of Adaptive Vision Library, version 4.10
// Copyright (C) 2018 Future Processing Sp. z o. o.
//
// This file should be included directly in your program.
//

#ifndef ThirdPartySdk_H
#define ThirdPartySdk_H

#include "ATL/Array.h"
#include "ATL/Array.hxx"
#include "ATL/Dummy.h"
#include "ATL/Error.h"
#include "ATL/Optional.h"
#include "AVLCommon/BaseState.h"
#include "AVLCommon/Config.h"
#include "AVLCommon/IoBaseState.h"
#include "AVLCommon/Settings.h"
#include "Cameras/AvSmart.h"
#include "Cameras/AXIS.h"
#include "Cameras/AXIS/AXISInterface.h"
#include "Cameras/BitFlow.h"
#include "Cameras/BitFlow/BitFlowInterface.h"
#include "Cameras/Ensenso.h"
#include "Cameras/Ensenso/EnsensoInterface.h"
#include "Cameras/Gocator.h"
#include "Cameras/Gocator/GocatorEnums.h"
#include "Cameras/Gocator/GocatorInterface.h"
#include "Cameras/Hikvision.h"
#include "Cameras/Hikvision/HikvisionInterface.h"
#include "Cameras/ICImagingControl.h"
#include "Cameras/ICImagingControl/ICImagingControlInterface.h"
#include "Cameras/ICube.h"
#include "Cameras/IDS.h"
#include "Cameras/IDS/IDSEnums.h"
#include "Cameras/IDS/IDSInterface.h"
#include "Cameras/IFM.h"
#include "Cameras/IFM/IfmInterface.h"
#include "Cameras/IFM/IfmParameters.h"
#include "Cameras/Kinect.h"
#include "Cameras/Kinect/KinectInterface.h"
#include "Cameras/Lumenera.h"
#include "Cameras/Lumenera/LumeneraInterface.h"
#include "Cameras/mvGenTLAcquire.h"
#include "Cameras/mvGenTLAcquire/mvGenTLAcquireEnums.h"
#include "Cameras/mvGenTLAcquire/mvGenTLAcquireInterface.h"
#include "Cameras/NetGmbh/ICubeInterface.h"
#include "Cameras/PointGrey.h"
#include "Cameras/PointGrey/PointGreyEnums.h"
#include "Cameras/PointGrey/PointGreyInterface.h"
#include "Cameras/Pylon.h"
#include "Cameras/Pylon/PylonInterface.h"
#include "Cameras/Roseek.h"
#include "Cameras/Roseek/RoseekInterface.h"
#include "Cameras/Smart.h"
#include "Cameras/Spinnaker.h"
#include "Cameras/Spinnaker/SpinnakerInterface.h"
#include "Cameras/SynView.h"
#include "Cameras/SynView/SynViewInterface.h"
#include "Cameras/SynView/SynViewParameters.h"
#include "Cameras/ThorLabs.h"
#include "Cameras/ThorLabs/ThorLabsInterface.h"
#include "Cameras/Vimba.h"
#include "Cameras/Vimba/VimbaInterface.h"
#include "Cameras/WebCamera.h"
#include "Cameras/WebCamera/WebCameraInputFormat.h"
#include "Cameras/WebCamera/WebCameraInterface.h"
#include "Cameras/XiApi.h"
#include "Cameras/xiApi/xiApiInterface.h"
#include "GenICam/GenICamTypes.h"
#include "Geometry/Geometry.h"
#include "Hardware/ADAMTCP.h"
#include "Hardware/AdamTCP/AdvantechAdamTCPInterface.h"
#include "Hardware/DAQmx.h"
#include "Hardware/DAQmx/DAQmxInterface.h"
#include "Hardware/DAQNavi.h"
#include "Hardware/DAQNavi/DAQNaviInterface.h"
#include "Hardware/ImagoTechnologies.h"
#include "Hardware/LEX.h"
#include "Hardware/LEX/LexInterface.h"
#include "Hardware/MultiCam.h"
#include "Hardware/MultiCam/MultiCamInterface.h"
#include "Hardware/Neousys.h"
#include "Hardware/Neousys/NeousysInterface.h"
#include "Hardware/VisionBox/VisionBoxInterface.h"
#include "Image/Image.h"

#endif // ThirdPartySdk_H
