#ifndef VISIONGRAPH_GLOBAL_H
#define VISIONGRAPH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VISIONGRAPH_LIBRARY)
#  define VISIONGRAPHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VISIONGRAPHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VISIONGRAPH_GLOBAL_H
